[package]
name = "stm32-test"
version = "0.1.0"
authors = ["Brian Schwind <brianmschwind@gmail.com>"]
edition = "2018"

[dependencies]
# The "medium" feature flag means "medium density", where "density" refers to the
# amount of features on a given microcontroller
# https://electronics.stackexchange.com/a/248187
stm32f1xx-hal = {version = "0.7", features = ["rt", "stm32f103", "medium", "stm32-usbd"] }
embedded-hal = "0.2"
cortex-m = "0.6"
cortex-m-rt = "0.6"
panic-halt = "0.2"
nb = "1"
panel-protocol = { git = "https://github.com/tonarino/panel-protocol.git", rev = "0.2" }
usb-device = "0.2"
usbd-serial = "0.1"
libm = "0.2"
