[package]
name = "stm32-test"
version = "0.1.0"
authors = ["Brian Schwind <brianmschwind@gmail.com>"]
edition = "2018"

[dependencies]
# The "medium" feature flag means "medium density", where "density" refers to the
# amount of features on a given microcontroller
# https://electronics.stackexchange.com/a/248187
panel-protocol = { path = "../panel-protocol" }
stm32f1xx-hal = {version = "0.6", features = ["rt", "stm32f103", "medium"] }
embedded-hal = "0.2"
arrayvec = { version = "0.5", default-features = false }
cortex-m = "0.6"
cortex-m-rt = "0.6"
panic-halt = "0.2"
nb = "1"
